#####ACLS-PORT-PROTOCOL-eq#####
  - name: ðŸš¦ ACLS
    pause:
      prompt: "[???] What is the number of packets you want to set for eq ? "
    register: ACLS_PORT_PROTOCOL_DATA
    when: ACLS_PORT_PROTOCOL.user_input == "eq"
#####ACLS-PORT-PROTOCOL-eq#####
