#------------------------------------------#ACLS#------------------------------------------#
  - name: ðŸš¦ ACLS | AFI
    debug:
      msg: "{{ ACLS_AFI.user_input }}"
    when: ACLS_AFI is defined

  - name: ðŸš¦ ACLS | GRANT
    debug:
      msg: "{{ ACLS_GRANT.user_input }}"
    when: ACLS_GRANT is defined

  - name: ðŸš¦ ACLS | SOURCE_IP
    debug:
      msg: "{{ ACLS_SOURCE_IP.user_input }}"
    when: ACLS_SOURCE_IP is defined

  - name: ðŸš¦ ACLS | SOURCE_WILD
    debug:
      msg: "{{ ACLS_SOURCE_WILD.user_input }}"
    when: ACLS_SOURCE_WILD is defined

  - name: ðŸš¦ ACLS | DEST_IP
    debug:
      msg: "{{ ACLS_DEST_IP.user_input }}"
    when: ACLS_DEST_IP is defined

  - name: ðŸš¦ ACLS | DEST_WILD
    debug:
      msg: "{{ ACLS_DEST_WILD.user_input }}"
    when: ACLS_DEST_WILD is defined

  - name: ðŸš¦ ACLS | PORT_PROTOCOL
    debug:
      msg: "{{ ACLS_PORT_PROTOCOL.user_input }}"
    when: ACLS_PORT_PROTOCOL is defined

  - name: ðŸš¦ ACLS | PORT_PROTOCOL_DATA
    debug:
      msg: "{{ ACLS_PORT_PROTOCOL_DATA.user_input }}"
    when: ACLS_PORT_PROTOCOL_DATA is defined

  - name: ðŸš¦ ACLS | DSCP
    debug:
      msg: "{{ ACLS_DSCP.user_input }}"
    when: ACLS_DSCP is defined

  - name: ðŸš¦ ACLS | TTL
    debug:
      msg: "{{ ACLS_TTL.user_input }}"
    when: ACLS_TTL is defined

  - name: ðŸš¦ ACLS | TTL_DATA
    debug:
      msg: "{{ ACLS_TTL_DATA.user_input }}"
    when: ACLS_TTL_DATA is defined

  - name: ACLS | cat ACLS
    debug:
      msg: "{{ ACLS_STATE.user_input }}"
#------------------------------------------#ACLS#------------------------------------------#
