#------------------------------------------#VLAN#------------------------------------------#
  - name: ðŸ”€ VLAN | NAME
    debug:
      msg: "{{ VLAN_NAME.user_input }}"
    when: VLAN_NAME is defined

  - name: ðŸ”€ VLAN | STATE
    debug:
      msg: "{{ VLAN_STATE.user_input }}"
    when: VLAN_STATE is defined

  - name: ðŸ”€ VLAN | ID
    debug:
      msg: "{{ VLAN_ID.user_input }}"
    when: VLAN_ID is defined

  - name: ðŸ”€ VLAN | SHUTDOWN
    debug:
      msg: "{{ VLAN_SHUTDOWN.user_input }}"
    when: VLAN_SHUTDOWN is defined

  - name: ðŸ”€ VLAN | MTU
    debug:
      msg: "{{ VLAN_MTU.user_input }}"
    when: VLAN_MTU is defined

  - name: ðŸ”€ VLAN | OPTIONS
    debug:
      msg: "{{ VLAN_OPTION.user_input }}"
    when: VLAN_OPTION is defined

#  - name: VLAN | REMOTE_SPAN
#    debug:
#      msg: "{{ VLAN_REMOTE_SPAN.user_input }}"
#------------------------------------------#VLAN#------------------------------------------#
